use_frameworks!

target 'UIButtonWithTouchInfo-Swift_Example' do
  pod 'UIButtonWithTouchInfo-Swift', :path => '../'

  target 'UIButtonWithTouchInfo-Swift_Tests' do
    inherit! :search_paths

    
  end
end
